# RPGHealthPlus v1.5.0
mobs-xp:
  BAT: 5
  BEE: 3
  BLAZE: 9
  CAVE_SPIDER: 6
  CHICKEN: 3
  COD: 3
  COW: 4
  CREEPER: 7
  DOLPHIN: 5
  DONKEY: 4
  DROWNED: 5
  ELDER_GUARDIAN: 15
  ENDERMAN: 9
  ENDERMITE: 5
  ENDER_DRAGON: 400
  EVOKER: 10
  FOX: 5
  GHAST: 11
  GIANT: 150
  GUARDIAN: 8
  HOGLIN: 8
  HORSE: 5
  HUSK: 6
  ILLUSIONER: 12
  IRON_GOLEM: 17
  LLAMA: 5
  MAGMA_CUBE: 6
  MULE: 4
  MUSHROOM_COW: 4
  OCELOT: 4
  PANDA: 5
  PARROT: 3
  PHANTOM: 8
  PIG: 4
  PIG_ZOMBIE: 8
  PIGLIN: 7
  PILLAGER: 6
  PLAYER: 50
  POLAR_BEAR: 6
  PUFFERFISH: 3
  RABBIT: 4
  RAVAGER: 18
  SALMON: 4
  SHEEP: 3
  SHULKER: 6
  SILVERFISH: 5
  SKELETON: 6
  SKELETON_HORSE: 7
  SLIME: 4
  SNOWMAN: 4
  SPIDER: 4
  SQUID: 4
  STRAY: 7
  STRIDER: 7
  TRADER_LLAMA: 5
  TROPICAL_FISH: 3
  TURTLE: 5
  VEX: 6
  VILLAGER: 7
  VINDICATOR: 8
  WANDERING_TRADER: 5
  WITCH: 10
  WITHER: 150
  WITHER_SKELETON: 10
  WOLF: 5
  ZOGLIN: 8
  ZOMBIE: 5
  ZOMBIE_HORSE: 7
  ZOMBIE_VILLAGER: 8
  ZOMBIFIED_PIGLIN: 7
names-xp:
- examplemobname1 = 14
- examplemobname2 = 12
nonaffected-worlds:
- exampleworldname1
- exampleworldname2
configuration:
  max-hp: 1000000000
  starting-hp: 15
  needed-xp-formula: 1*HP
  xp-lost-on-death-formula: 5
  xp-percentage-from-mobspawners: 50
  hp-display-scale: 1
  enable-names-xp: true
  minimum-level-to-earn-xp: 0
  multiply-gained-xp-with-levels: false
  show-xp-holograms: true
  xp-holograms-time: 40
  disable-in-creative: false
  reset-hp-on-death: false
  use-hp-based-damage-multiplier: true
  melee-damage-multiplier: 2.0
  use-groups-permissions: false
  heal-after-world-change: false
  heal-after-level-up: true
  enable-sounds: true
  check-for-updates: true
